/**
 * Russian copy for Phase 1 — all user-facing text.
 */

export const ru = {
  // App
  appName: 'МарТик',
  envMissingTitle: 'Не заданы переменные Supabase',
  envMissingBody:
    'В панели хостинга (Vercel, Netlify, Cloudflare Pages, GitHub Actions и т.д.) добавьте переменные окружения и пересоберите проект.',
  envMissingVars:
    'Нужны: VITE_SUPABASE_URL (полная ссылка вида https://xxxx.supabase.co) и VITE_SUPABASE_ANON_KEY (ключ anon). Supabase → Project Settings → API.',
  envMissingLocal: 'Локально создайте файл .env в корне проекта (см. .env.example).',
  envWrongPostgresUrl:
    'Похоже, в VITE_SUPABASE_URL попала строка подключения к базе (postgresql://… или порт :5432). В браузере нужна другая ссылка: Supabase → Project Settings → API → скопируйте Project URL — вид https://xxxx.supabase.co (без db. и без :5432).',
  envVarsSwapped:
    'Перепутаны переменные: в VITE_SUPABASE_URL должна быть только ссылка вида https://xxxx.supabase.co (Project URL). В VITE_SUPABASE_ANON_KEY — только ключ sb_publishable_... (Publishable key). Поменяйте местами в Netlify, сохраните и сделайте новый деплой.',

  // Auth
  login: 'Войти',
  signUp: 'Регистрация',
  email: 'Email',
  password: 'Пароль',
  confirmPassword: 'Подтвердите пароль',
  forgotPassword: 'Забыли пароль?',
  noAccount: 'Нет аккаунта? Зарегистрироваться',
  hasAccount: 'Уже есть аккаунт? Войти',
  authError: 'Ошибка входа. Проверьте email и пароль.',
  signUpError: 'Ошибка регистрации.',
  signupSuccessConfirmEmail: 'Регистрация прошла успешно. Подтвердите email по ссылке из письма.',
  errorEmailNotConfirmed: 'Сначала подтвердите email по ссылке из письма (проверьте «Спам»).',
  errorInvalidApiKey:
    'Ошибка 401: неверный ключ API. В Netlify в VITE_SUPABASE_ANON_KEY вставьте anon public ключ из Supabase → Settings → API (длинная строка, обычно начинается с eyJ…). Не используйте service_role и не путайте с паролем от базы.',
  errorUserExists: 'Этот email уже зарегистрирован.',
  errorRateLimit: 'Слишком много попыток. Попробуйте позже.',
  errorInvalidLogin: 'Неверный email или пароль.',
  signOut: 'Выйти',
  passwordsMismatch: 'Пароли не совпадают.',
  loginPrompt: 'Войдите в аккаунт',
  signUpPrompt: 'Создайте аккаунт',

  // Nav
  navHome: 'Главная',
  navToday: 'Сегодня',
  navDiary: 'Дневник',
  navSettings: 'Настройки',
  navBeauty: 'Красота',
  navWardrobe: 'Гардероб',
  navWishlist: 'Вишлист',

  // Wishlist
  wishlistTitle: 'Вишлист',
  wishlistSubtitle: 'Сохраняйте идеи до покупки, затем переносите в нужный раздел.',
  wishlistAdd: 'Добавить в вишлист',
  wishlistEdit: 'Редактировать желание',
  wishlistTargetKind: 'Куда попадёт после покупки',
  wishlistKindCosmetics: 'Косметика',
  wishlistKindClothing: 'Одежда',
  wishlistKindVitamin: 'Витамины',
  wishlistKindProduct: 'Товары',
  wishlistMarkOwned: 'Купила / в коллекцию',
  wishlistMarkOwnedConfirm: 'Перенести в выбранный раздел? Позже можно поставить оценки там, где они предусмотрены.',
  wishlistMoveError: 'Не удалось перенести',
  wishlistMovedHint: 'Готово. Откройте раздел «Красота», «Гардероб» или витамины.',
  wishlistEmpty: 'Вишлист пуст',
  wishlistFilterAll: 'Все типы',
  wishlistDeleteConfirm: 'Удалить из вишлиста?',
  wishlistMetaHintCosmetics: 'Подсказки для косметики (можно уточнить до переноса)',
  wishlistMetaHintClothing: 'Параметры вещи',
  wishlistMetaHintVitamin: 'Дозировка',
  wishlistPriceNote: 'Цена',

  // Wardrobe (Phase 3A)
  wardrobeTitle: 'Гардероб',
  wardrobeAddItem: 'Добавить вещь',
  wardrobeEditItem: 'Редактировать',
  wardrobeItemName: 'Название',
  wardrobeItemNamePlaceholder: 'Например: Белая льняная рубашка',
  wardrobeCategory: 'Категория',
  wardrobeCategoryPlaceholder: 'Выберите категорию',
  wardrobeCategoryTop: 'Верх',
  wardrobeCategoryBottom: 'Низ',
  wardrobeCategoryDress: 'Платье',
  wardrobeCategoryShoes: 'Обувь',
  wardrobeCategoryAccessory: 'Аксессуар',
  wardrobeColor: 'Цвет',
  wardrobeColorPlaceholder: 'Например: белый, синий',
  wardrobeSeason: 'Сезон',
  wardrobeSeasonPlaceholder: 'Например: лето, зима',
  wardrobeNotes: 'Заметки',
  wardrobeNotesPlaceholder: 'Опционально',
  wardrobePhoto: 'Фото',
  wardrobePhotoAdd: 'Добавить фото',
  wardrobePhotoInvalidType: 'Выберите изображение (JPEG, PNG, WebP или GIF)',
  wardrobeNameRequired: 'Введите название',
  noWardrobeItems: 'Пока нет вещей. Добавьте первую — загрузите фото и заполните данные.',
  noWardrobeFilter: 'Нет вещей по выбранному фильтру.',
  deleteWardrobeItemConfirm: 'Удалить эту вещь?',
  wardrobeItemDeleted: 'Вещь удалена',

  // Outfit Builder (Phase 3B)
  myOutfits: 'Мои образы',
  newOutfit: 'Новый образ',
  outfitName: 'Название образа',
  outfitNamePlaceholder: 'Например: Образ на кофе',
  outfitNotes: 'Заметки',
  outfitNotesPlaceholder: 'Опционально',
  saveOutfit: 'Сохранить образ',
  editOutfit: 'Редактировать образ',
  slotTop: 'Верх',
  slotBottom: 'Низ',
  slotDress: 'Платье',
  slotOuterwear: 'Верхняя одежда',
  slotShoes: 'Обувь',
  slotAccessory: 'Аксессуар',
  outfitCoverPhotoOptional: 'Фото образа (необязательно)',
  outfitLookImageHint: 'Основное фото образа — отображается в карточке, в планировании и на главной.',
  outfitSavedSuccess: 'Образ сохранён!',
  assignToSlot: 'Выберите вещь',
  noItemInSlot: 'Добавить',
  deleteOutfitConfirm: 'Удалить этот образ?',
  outfitDeleted: 'Образ удалён',
  noOutfits: 'Пока нет образов. Создайте первый — выберите вещи из гардероба по слотам.',
  backToWardrobe: 'В гардероб',

  // Outfit planning by date (Phase 3C)
  planOutfit: 'Запланировать',
  planOutfitTitle: 'Запланировать образ на дату',
  plannedDate: 'Дата',
  savePlan: 'Сохранить',
  plannedOutfitSaved: 'Образ запланирован',
  plannedOutfitSavedOn: 'Образ запланирован на',
  dateAlreadyHasOutfit: 'На эту дату уже запланирован образ',
  replaceOutfit: 'Заменить',
  clearFromDate: 'Снять с даты',
  clearFromDateConfirm: 'Снять образ с этой даты?',
  outfitRemovedFromDate: 'Образ снят с даты',
  viewByDate: 'По дате',
  plannedByDateTitle: 'Образ на дату',
  selectDate: 'Выберите дату',
  noPlannedOutfitForDate: 'На эту дату образ не запланирован',
  plannedOutfitFor: 'Запланированный образ на',
  onThisDatePlanned: 'На эту дату запланирован образ',
  pickOutfitToReplace: 'Выберите образ для замены',
  ok: 'ОК',

  // Beauty (Phase 2A)
  beautyTitle: 'Красота',
  beautyProductLibrary: 'Мои продукты',
  addProduct: 'Добавить продукт',
  editProduct: 'Редактировать',
  productName: 'Название',
  productNamePlaceholder: 'Например: Витамин C сыворотка',
  productCategory: 'Категория',
  productCategoryPlaceholder: 'Выберите категорию',
  productArea: 'Зона',
  productAreaFace: 'Лицо',
  productAreaHair: 'Волосы',
  productAreaBody: 'Тело',
  productTimeOfDay: 'Время использования',
  productTimeMorning: 'Утро',
  productTimeEvening: 'Вечер',
  productTimeAnytime: 'Любое время',
  productNotes: 'Заметки',
  productNotesPlaceholder: 'Опционально',
  productPhoto: 'Фото',
  productPhotoAdd: 'Добавить фото',
  productPhotoInvalidType: 'Выберите изображение (JPEG, PNG, WebP или GIF)',
  productNameRequired: 'Введите название продукта',
  noProducts: 'Пока нет продуктов. Добавьте первый — это займёт минуту.',
  noProductsFilter: 'Нет продуктов по выбранным фильтрам.',
  filterAll: 'Все',
  deleteProductConfirm: 'Удалить этот продукт?',
  productDeleted: 'Продукт удалён',
  productCategoryCleanser: 'Очищение',
  productCategorySerum: 'Сыворотка',
  productCategoryMoisturizer: 'Увлажнение',
  productCategorySunscreen: 'Солнцезащита',
  productCategoryMask: 'Маска',
  productCategoryToner: 'Тонер',
  productCategoryHair: 'Волосы',
  productCategoryOther: 'Другое',
  productCategoryHousehold: 'Товары для дома и прочее',

  // Beauty routines (Phase 2B)
  beautyRoutines: 'Мои рутины',
  addRoutine: 'Добавить рутину',
  routineName: 'Название рутины',
  routineNamePlaceholder: 'Например: Утренний уход',
  routineType: 'Тип',
  routineTypeMorning: 'Утро',
  routineTypeEvening: 'Вечер',
  routineTypeHair: 'Волосы',
  routineTypeCustom: 'Своя',
  routineSteps: 'Шаги',
  routineRating: 'Оценка рутины',
  addStep: 'Добавить шаг',
  removeStep: 'Убрать',
  noRoutines: 'Пока нет рутин. Создайте первую — утро, вечер или уход за волосами.',
  noSteps: 'Нет шагов',
  deleteRoutineConfirm: 'Удалить эту рутину?',
  routineDeleted: 'Рутина удалена',
  pickProduct: 'Выберите продукт',
  noProductsForStep: 'Сначала добавьте продукты в библиотеку.',
  routineNameRequired: 'Введите название рутины',
  moveUp: 'Вверх',
  moveDown: 'Вниз',

  // Phase 2F: routine scheduling
  scheduleTitle: 'Повтор',
  cadenceNone: 'Без расписания (каждый день)',
  cadenceDaily: 'Каждый день',
  cadenceWeekly: 'По дням недели',
  cadenceMonthly: 'По числам месяца',
  scheduleWeekdays: 'Дни недели',
  scheduleMonthDays: 'Числа месяца',
  scheduleMonthDaysPlaceholder: 'Например: 1, 15',
  scheduleActive: 'Рутина активна',
  weekdaySun: 'Вс',
  weekdayMon: 'Пн',
  weekdayTue: 'Вт',
  weekdayWed: 'Ср',
  weekdayThu: 'Чт',
  weekdayFri: 'Пт',
  weekdaySat: 'Сб',

  productsTab: 'Продукты',
  routinesTab: 'Рутины',
  progressTab: 'Прогресс',

  // Beauty progress photos (Phase 2D)
  progressTitle: 'Фото прогресса',
  progressSubtitle: 'Лицо и волосы по дням',
  addProgressPhoto: 'Добавить фото',
  uploadFacePhoto: 'Фото лица',
  uploadHairPhoto: 'Фото волос',
  progressNotes: 'Заметки',
  progressNotesPlaceholder: 'Опционально',
  progressPhotoFor: 'Фото за',
  noProgressPhotos: 'Пока нет фото прогресса. Добавьте первое.',
  deleteProgressConfirm: 'Удалить это фото?',
  progressAreaFace: 'Лицо',
  progressAreaHair: 'Волосы',
  progressPickDate: 'Дата',
  progressUploading: 'Загрузка...',

  // Phase 2E: progress metadata
  progressRelatedRoutine: 'Связанная рутина',
  progressNoRoutine: 'Без рутины',
  progressFaceCondition: 'Состояние кожи',
  progressHairQuality: 'Состояние волос',
  progressHairLengthFeeling: 'Ощущение длины',
  ratingLow: 'Не очень',
  ratingMedium: 'Нормально',
  ratingGood: 'Хорошо',
  ratingGreat: 'Отлично',
  progressEdit: 'Изменить',

  // Beauty on Today (Phase 2C)
  beautyRoutineToday: 'Уход за собой',
  beautyRoutineMorning: 'Утро',
  beautyRoutineEvening: 'Вечер',
  beautyRoutineOther: 'Дополнительно',
  beautySlotEmptyMorning: 'Утренней рутины на сегодня нет. Добавь в разделе «Красота».',
  beautySlotEmptyEvening: 'Вечерней рутины на сегодня нет. Добавь в разделе «Красота».',
  beautyMorningDoneShort: 'Утренний уход сделан',
  beautyEveningDoneShort: 'Вечерний уход сделан',
  beautyOtherDoneShort: 'Дополнительные шаги сделаны',
  beautySlotHint: 'Отметьте выполненные шаги',
  vitaminsTitle: 'Витамины',
  beautyRoutineTodayHint: 'Отметьте выполненные шаги рутины на сегодня',
  beautyStreakPraiseTitle: 'Сегодня весь уход сделан — ты молодец!',
  beautyStreakLine: 'Ты уже делаешь это {days} дн. подряд.',
  beautyStreakMorningLine: 'Утром: {days} дн. подряд.',
  beautyStreakEveningLine: 'Вечером: {days} дн. подряд.',
  beautyStreakToHabit: 'До привычки осталось ещё {left} дн. (цель — 21 день подряд).',
  beautyStreakToHabitMorning: 'До привычки утром: ещё {left} дн. (цель — 21 день подряд).',
  beautyStreakToHabitEvening: 'До привычки вечером: ещё {left} дн. (цель — 21 день подряд).',
  beautyStreakHabitFormed: 'Уже больше 21 дня подряд — привычка крепнет!',
  beautyStreakShowSteps: 'Показать шаги, чтобы изменить',
  beautyStreakHideSteps: 'Свернуть список',
  markStepDone: 'Отметить выполненным',
  noRoutinesForToday: 'Нет рутин. Создайте их в разделе «Красота».',

  // Home
  goodMorning: 'Доброе утро',
  goodAfternoon: 'Добрый день',
  goodEvening: 'Добрый вечер',
  planYourLook: 'Запланировать образ',
  noOutfitPlanned: 'На сегодня образ не запланирован',
  avatarNoOutfitChosen: 'Как хочется выглядеть сегодня?',
  avatarPickOutfit: 'Выбрать образ',
  lookOfTheDay: 'образ дня',
  homeOutfitTitle: 'Образ',
  openToday: 'Перейти к дню',
  beautyRoutine: 'Уход',
  focus: 'Фокус',
  addNote: 'Записать',
  homeTasksWord: 'задач',
  homeStepsCompleted: 'шагов',
  homeTasksCompleted: 'выполнено',
  homeTasksOpen: 'в списке на сегодня',
  comingSoonBeauty: 'Скоро: уход и рутины',
  comingSoonFocus: 'Скоро: фокус и таймер',

  // Day state
  dayStateEmpty: 'Ещё пустой',
  dayStateStarted: 'Начинается',
  dayStateForming: 'Складывается',
  dayStateAlmost: 'Почти собран',
  dayStateComplete: 'Собран',
  dayStateEmptySub: 'С чего начнём день?',
  dayStateStartedSub: 'Что-то уже есть.',
  dayStateFormingSub: 'День набирает форму.',
  dayStateAlmostSub: 'Почти всё на месте.',
  dayStateCompleteSub: 'День собран. Можно выдохнуть.',
  dayStateLabel: 'Как складывается день',

  // Home empty states
  homeFocusEmpty: 'Что одно важно сегодня?',
  homeFocusNoOpenTasks: 'Открытых задач нет.',
  homeFocusDone: 'Всё сделано.',
  homeFocusPartial: 'выполнено',
  homeCareEmpty: 'Ещё не начато. Можно сейчас.',
  homeCareAllDone: 'Уход сделан.',
  homeCareNoScheduledToday: 'Сегодня по расписанию рутин нет.',
  homeCareMorningEvening: 'Уход за месяц: утро и вечер',
  homeCareMorningShort: 'Утро',
  homeCareEveningShort: 'Вечер',
  homeCareStepsLeft: 'Осталось шагов',
  homeOutfitEmpty: 'Как хочется выглядеть сегодня?',
  homeWaterEmpty: 'Первый стакан — самый лёгкий шаг.',
  homeWaterDone: 'Тело поддержано.',

  // After-action feedback
  feedbackWater: 'Хорошо. Тело замечает.',
  feedbackRoutine: 'Сделано. Это имеет значение.',
  feedbackTask: 'Готово.',
  feedbackOutfit: 'День обрёл облик.',
  feedbackJournal: 'Слова сохранены.',

  // Recovery
  recoveryBack: 'С возвращением. Сегодня — новый день.',

  // Today
  today: 'Сегодня',
  yesterday: 'Вчера',
  tomorrow: 'Завтра',
  dateTodayPrefix: 'Сегодня, ',
  journal: 'Заметки дня',
  journalShortLabel: 'Заметки',
  journalPlaceholder: 'Как прошёл день?',
  mood: 'Настроение',
  moodPlaceholder: 'Как ты сейчас?',
  tasks: 'Задачи',
  addTask: 'Добавить',
  tasksHideCompletedTitle: 'Скрыть выполненные',
  tasksShowCompletedTitle: 'Показать выполненные',
  tasksCompletedHiddenHint: 'Выполненные скрыты. Нажми кнопку с глазом в шапке списка.',
  taskPlaceholder: 'Что важно сегодня?',
  noTasks: 'Что одно важно сегодня? Запиши — и это уже начало.',
  viewInDiary: 'Открыть в дневнике',

  // Evening summary
  eveningSummaryTitle: 'Как прошёл день',
  eveningSummaryLink: 'Записать итог',

  // Water
  water: 'Вода',
  waterMonthHint: 'Нет · частично · норма',
  addWater: '+250 мл',
  waterGoal: 'Цель',
  saved: 'Сохранено',

  // Diary
  diary: 'Дневник',
  pastDays: 'Прошедшие дни',
  noEntries: 'Пока нет записей',
  pickDate: 'Выберите дату',

  // Settings
  settings: 'Настройки',
  waterGoalLabel: 'Дневная норма воды (мл)',
  timezoneLabel: 'Часовой пояс',
  profile: 'Профиль',
  displayName: 'Имя',

  // Common
  save: 'Сохранить',
  cancel: 'Отмена',
  delete: 'Удалить',
  loading: 'Загрузка...',
  error: 'Что-то пошло не так',
} as const
