/**
 * Russian copy for Phase 1 — all user-facing text.
 */

export const ru = {
  // App
  appName: 'МарТик',

  // Auth
  login: 'Войти',
  signUp: 'Регистрация',
  email: 'Email',
  password: 'Пароль',
  confirmPassword: 'Подтвердите пароль',
  forgotPassword: 'Забыли пароль?',
  noAccount: 'Нет аккаунта? Зарегистрироваться',
  hasAccount: 'Уже есть аккаунт? Войти',
  authError: 'Ошибка входа. Проверьте email и пароль.',
  signUpError: 'Ошибка регистрации.',
  signupSuccessConfirmEmail: 'Регистрация прошла успешно. Подтвердите email по ссылке из письма.',
  errorUserExists: 'Этот email уже зарегистрирован.',
  errorRateLimit: 'Слишком много попыток. Попробуйте позже.',
  errorInvalidLogin: 'Неверный email или пароль.',
  signOut: 'Выйти',
  passwordsMismatch: 'Пароли не совпадают.',
  loginPrompt: 'Войдите в аккаунт',
  signUpPrompt: 'Создайте аккаунт',

  // Nav
  navHome: 'Главная',
  navToday: 'Сегодня',
  navDiary: 'Дневник',
  navSettings: 'Настройки',
  navBeauty: 'Красота',
  navWardrobe: 'Гардероб',

  // Beauty (Phase 2A)
  beautyTitle: 'Красота',
  beautyProductLibrary: 'Мои продукты',
  addProduct: 'Добавить продукт',
  editProduct: 'Редактировать',
  productName: 'Название',
  productNamePlaceholder: 'Например: Витамин C сыворотка',
  productCategory: 'Категория',
  productCategoryPlaceholder: 'Выберите категорию',
  productArea: 'Зона',
  productAreaFace: 'Лицо',
  productAreaHair: 'Волосы',
  productAreaBody: 'Тело',
  productTimeOfDay: 'Время использования',
  productTimeMorning: 'Утро',
  productTimeEvening: 'Вечер',
  productTimeAnytime: 'Любое время',
  productNotes: 'Заметки',
  productNotesPlaceholder: 'Опционально',
  productPhoto: 'Фото',
  productPhotoAdd: 'Добавить фото',
  productPhotoInvalidType: 'Выберите изображение (JPEG, PNG, WebP или GIF)',
  productNameRequired: 'Введите название продукта',
  noProducts: 'Пока нет продуктов. Добавьте первый — это займёт минуту.',
  noProductsFilter: 'Нет продуктов по выбранным фильтрам.',
  filterAll: 'Все',
  deleteProductConfirm: 'Удалить этот продукт?',
  productDeleted: 'Продукт удалён',
  productCategoryCleanser: 'Очищение',
  productCategorySerum: 'Сыворотка',
  productCategoryMoisturizer: 'Увлажнение',
  productCategorySunscreen: 'Солнцезащита',
  productCategoryMask: 'Маска',
  productCategoryToner: 'Тонер',
  productCategoryHair: 'Волосы',
  productCategoryOther: 'Другое',

  // Beauty routines (Phase 2B)
  beautyRoutines: 'Мои рутины',
  addRoutine: 'Добавить рутину',
  routineName: 'Название рутины',
  routineNamePlaceholder: 'Например: Утренний уход',
  routineType: 'Тип',
  routineTypeMorning: 'Утро',
  routineTypeEvening: 'Вечер',
  routineTypeHair: 'Волосы',
  routineTypeCustom: 'Своя',
  routineSteps: 'Шаги',
  addStep: 'Добавить шаг',
  removeStep: 'Убрать',
  noRoutines: 'Пока нет рутин. Создайте первую — утро, вечер или уход за волосами.',
  noSteps: 'Нет шагов',
  deleteRoutineConfirm: 'Удалить эту рутину?',
  routineDeleted: 'Рутина удалена',
  pickProduct: 'Выберите продукт',
  noProductsForStep: 'Сначала добавьте продукты в библиотеку.',
  routineNameRequired: 'Введите название рутины',
  moveUp: 'Вверх',
  moveDown: 'Вниз',

  // Phase 2F: routine scheduling
  scheduleTitle: 'Повтор',
  cadenceNone: 'Без расписания (каждый день)',
  cadenceDaily: 'Каждый день',
  cadenceWeekly: 'По дням недели',
  cadenceMonthly: 'По числам месяца',
  scheduleWeekdays: 'Дни недели',
  scheduleMonthDays: 'Числа месяца',
  scheduleMonthDaysPlaceholder: 'Например: 1, 15',
  scheduleActive: 'Рутина активна',
  weekdaySun: 'Вс',
  weekdayMon: 'Пн',
  weekdayTue: 'Вт',
  weekdayWed: 'Ср',
  weekdayThu: 'Чт',
  weekdayFri: 'Пт',
  weekdaySat: 'Сб',

  productsTab: 'Продукты',
  routinesTab: 'Рутины',
  progressTab: 'Прогресс',

  // Beauty progress photos (Phase 2D)
  progressTitle: 'Фото прогресса',
  progressSubtitle: 'Лицо и волосы по дням',
  addProgressPhoto: 'Добавить фото',
  uploadFacePhoto: 'Фото лица',
  uploadHairPhoto: 'Фото волос',
  progressNotes: 'Заметки',
  progressNotesPlaceholder: 'Опционально',
  progressPhotoFor: 'Фото за',
  noProgressPhotos: 'Пока нет фото прогресса. Добавьте первое.',
  deleteProgressConfirm: 'Удалить это фото?',
  progressAreaFace: 'Лицо',
  progressAreaHair: 'Волосы',
  progressPickDate: 'Дата',
  progressUploading: 'Загрузка...',

  // Phase 2E: progress metadata
  progressRelatedRoutine: 'Связанная рутина',
  progressNoRoutine: 'Без рутины',
  progressFaceCondition: 'Состояние кожи',
  progressHairQuality: 'Состояние волос',
  progressHairLengthFeeling: 'Ощущение длины',
  ratingLow: 'Не очень',
  ratingMedium: 'Нормально',
  ratingGood: 'Хорошо',
  ratingGreat: 'Отлично',
  progressEdit: 'Изменить',

  // Beauty on Today (Phase 2C)
  beautyRoutineToday: 'Уход за собой',
  beautyRoutineTodayHint: 'Отметьте выполненные шаги рутины на сегодня',
  markStepDone: 'Отметить выполненным',
  noRoutinesForToday: 'Нет рутин. Создайте их в разделе «Красота».',

  // Home
  goodMorning: 'Доброе утро',
  goodAfternoon: 'Добрый день',
  goodEvening: 'Добрый вечер',
  planYourLook: 'Запланировать образ',
  noOutfitPlanned: 'На сегодня образ не запланирован',
  openToday: 'Перейти к дню',
  beautyRoutine: 'Уход',
  focus: 'Фокус',
  addNote: 'Добавить заметку',
  comingSoonBeauty: 'Скоро: уход и рутины',
  comingSoonFocus: 'Скоро: фокус и таймер',

  // Today
  today: 'Сегодня',
  yesterday: 'Вчера',
  tomorrow: 'Завтра',
  dateTodayPrefix: 'Сегодня, ',
  journal: 'Заметки дня',
  journalPlaceholder: 'Как прошёл день?',
  mood: 'Настроение',
  moodPlaceholder: 'Выберите настроение',
  tasks: 'Задачи',
  addTask: 'Добавить задачу',
  taskPlaceholder: 'Название задачи',
  noTasks: 'Пока нет задач',
  viewInDiary: 'Открыть в дневнике',

  // Water
  water: 'Вода',
  addWater: '+250 мл',
  waterGoal: 'Цель',
  saved: 'Сохранено',

  // Diary
  diary: 'Дневник',
  pastDays: 'Прошедшие дни',
  noEntries: 'Пока нет записей',
  pickDate: 'Выберите дату',

  // Settings
  settings: 'Настройки',
  waterGoalLabel: 'Дневная норма воды (мл)',
  timezoneLabel: 'Часовой пояс',
  profile: 'Профиль',
  displayName: 'Имя',

  // Common
  save: 'Сохранить',
  cancel: 'Отмена',
  delete: 'Удалить',
  loading: 'Загрузка...',
  error: 'Что-то пошло не так',
} as const
